name: flutter_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  file_picker: ^6.2.1
  cached_network_image: ^3.4.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/turan_symbol.png
    - assets/brand/turan_pattern.png
    - assets/math/sat_math_reference.png
